[package]
name = "kvs"
version = "0.1.0"
authors = ["Chris Dawes <cmsd2@cantab.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"

[[bin]]
name = "kvs"
test = false
doctest = false

[lib]
test = false
doctest = false
